package com.smackchat.juansandoval.smackchat.utils

const val BASE_URL = "https://jsandovalchat.herokuapp.com/v1/"
const val URL_REGISTER = "${BASE_URL}account/register"
const val URL_LOGIN = "${BASE_URL}account/login"
const val URL_CREATE_USER = "${BASE_URL}user/add"
const val DRAWABLE_RESOURCE = "drawable"
const val USER_DRAWABLE_COLOR = "[0.5, 0.5, 0.5, 1]"
const val USER_AVATAR_DEFAULT = "profileDefault"
const val USER_DARK_AVATAR = "dark"
const val USER_LIGHT_AVATAR = "light"
const val EXTRA_USERNAME = "username"
const val EXTRA_EMAIL = "email"
const val EXTRA_PASSWORD = "password"
const val EXTRA_USER = "user"
const val EXTRA_NAME = "name"
const val EXTRA_AVATAR_NAME = "avatarName"
const val EXTRA_AVATAR_COLOR = "avatarColor"
const val EXTRA_ID = "_id"
const val EXTRA_TOKEN = "token"
const val EXTRA_AUTHORIZATION = "Authorization"
const val EXTRA_BEARER  = "Bearer "
const val JSON_APPLICATION_TYPE = "application/json; charset=utf-8"